[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
lisk-sepolia = "${LISK_SEPOLIA_RPC_URL}"

[etherscan]
lisk-sepolia = { key = "${BLOCKSCOUT_API_KEY}", url = "https://sepolia-blockscout.lisk.com/api", chain = 4202 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# DEPLOY COMMAND
# forge script script/DeployV2.s.sol:DeployV2Script --rpc-url $LISK_SEPOLIA_RPC_URL --broadcast --verify -vvvv